[26/Aug/2022 18:50:46] ERROR [django.request:224] Internal Server Error: /
Traceback (most recent call last):
  File "D:\Myprojects\Django Projects\Email_service\evenv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Myprojects\Django Projects\Email_service\evenv\lib\site-packages\django\core\handlers\base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "D:\Myprojects\Django Projects\Email_service\evenv\lib\site-packages\django\core\handlers\base.py", line 309, in check_response
    raise ValueError(
ValueError: The view app.views.email_sending_func didn't return an HttpResponse object. It returned None instead.
